### ISSUE TITLE
payment-v2 endpoint test hard to PR from my fork - please replace app.test.js with this code to bee-travels/bee-travels-node MASTER br

### ISSUE THREAD

**Issue by Grant-Steinfeld** [bee-travels/bee-travels-node#167]
PR from bee-travels/bee-travels-node to my fork had merge conflicts I just could not resolve at this early hour :)

[app.test.js.zip](https://github.com/bee-travels/bee-travels-node/files/4735325/app.test.js.zip)

**Comment by MaxShapiro32** [comment]
Adding it to my fork
