### ISSUE TITLE
Checkout should have transaction time stored

### ISSUE THREAD

**Issue by moficodes** [bee-travels/bee-travels-node#189]
Right now we do not store the transaction time at the time of writing to checkout database. 

This is a important data point and should be added.

**Comment by moficodes** [comment]
add a field `created_at` for transaction

**Comment by MaxShapiro32** [comment]
Already implemented here: https://github.com/bee-travels/bee-travels-node/blob/master/services/checkout-v2/src/services/postgresService.js#L13
