### ISSUE TITLE
Hotel Searching using Filters

### ISSUE THREAD

**Issue by MaxShapiro32** [bee-travels/bee-travels-node#25]
Have filters to search hotels in a destination by rating, super-chain, price, etc.

**Comment by MaxShapiro32** [comment]
Price Surge on last minute booking (e.g. 2x for next day, up-to 1.75x for the last week)

Each city has a base price and a multiplier. The final prices will be the “multiplication of base_rate_of_city x price_multiplier x surge_price_multiplier”

**Comment by moficodes** [comment]
I think surge prices and any kind of discount operation should be left to cart or the aggregator ui.

hotel service to me seem like a place for absolute prices. 

also the first version does not deal with inventory or occupancy. 

#81 adds basic hotel service.
