### ISSUE TITLE
Checkout Service Node.js Version

### ISSUE THREAD

**Issue by MaxShapiro32** [bee-travels/bee-travels-node#52]
Create the Node.js version of the Checkout/Cart Services

**Comment by Grant-Steinfeld** [comment]
Security important for privacy of personal information used for  Payments

**Comment by MaxShapiro32** [comment]
Moved Payment Service to #106 due to v1.1

**Comment by MaxShapiro32** [comment]
Taking this over from Grant's PR #173

**Comment by MaxShapiro32** [comment]
Service is done. Will create a PR for this and a separate PR for the email HTML template
