### ISSUE TITLE
Hotel/Flight/Car Rental Services DevOps Story

### ISSUE THREAD

**Issue by MaxShapiro32** [bee-travels/bee-travels-node#64]
Create a DevOps Story around the Hotel/Flight/Car Rental Services

**Comment by bourdakos1** [comment]
you are killing me 
<img width="767" alt="Screen Shot 2019-12-06 at 1 40 45 PM" src="https://user-images.githubusercontent.com/4212769/70347217-0cc4ae80-182e-11ea-81d7-a1d400d8ed53.png">

**Comment by jjasghar** [comment]
Sure! I think I need to talk to yall to make sure i understand, can we set up some time next week to talk?

**Comment by MaxShapiro32** [comment]
@jjasghar I think it will be best to discuss this with @moficodes as well. We can discuss this in January when we are all back from vacations/holidays.
