### ISSUE TITLE
Best practices with modern Node development

### ISSUE THREAD

**Issue by MaxShapiro32** [bee-travels/bee-travels-node#77]
Article discussing Best practices with modern Node development

Code pattern Issue: https://github.ibm.com/IBMCode/IBMCodeContent/issues/3602

**Comment by Grant-Steinfeld** [comment]
title of blog changed to **A primer on Test-driven development**

**Comment by MaxShapiro32** [comment]
Done and published here: https://developer.ibm.com/articles/5-steps-of-test-driven-development/
